/*==============================================================================
SAMPLE DATA - OpenAI Data Engineering
Realistic synthetic OpenAI API responses covering:
  - Chat Completions (text, tool calls, multi-turn, refusals)
  - Batch API output (wrapped completions with custom_id)
  - Usage API buckets (time-series token consumption)
==============================================================================*/

USE SCHEMA SNOWFLAKE_EXAMPLE.OPENAI_DATA_ENG;

-------------------------------------------------------------------------------
-- CHAT COMPLETIONS: Standard text responses
-------------------------------------------------------------------------------

INSERT INTO RAW_CHAT_COMPLETIONS (source_file, raw)
SELECT 'api_log_2026-02-20.jsonl', PARSE_JSON(column1) FROM VALUES

-- Simple text completion
('{"id":"chatcmpl-9a1b2c3d","object":"chat.completion","created":1740067200,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"Snowflake''s VARIANT data type stores semi-structured data in a compressed columnar format, supporting up to 16 MB per value. It automatically handles schema detection and enables dot-notation traversal for JSON, Avro, Parquet, and XML.","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":42,"completion_tokens":58,"total_tokens":100,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_a1b2c3d4"}'),

-- Longer analytical response
('{"id":"chatcmpl-e4f5g6h7","object":"chat.completion","created":1740067260,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"Based on the Q4 earnings data, revenue grew 12% year-over-year to $2.1B. Key drivers include: (1) cloud migration acceleration in financial services, (2) 34% growth in consumption-based contracts, and (3) expansion in the APAC region. Operating margins improved 200bps to 28%. The forward guidance of $2.3-2.4B for Q1 suggests continued momentum, though macro headwinds in European markets warrant monitoring.","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":1250,"completion_tokens":312,"total_tokens":1562,"prompt_tokens_details":{"cached_tokens":1024,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":128,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_e4f5g6h7"}'),

-- Short factual response
('{"id":"chatcmpl-i8j9k0l1","object":"chat.completion","created":1740067320,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"The current UTC time would be needed from a real-time source. I don''t have access to live clocks.","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":18,"completion_tokens":24,"total_tokens":42,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_i8j9k0l1"}'),

-- Content filter triggered
('{"id":"chatcmpl-m2n3o4p5","object":"chat.completion","created":1740067380,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":null,"refusal":"I''m unable to help with that request as it involves generating content that could be harmful."},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":35,"completion_tokens":22,"total_tokens":57,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_m2n3o4p5"}'),

-- Max tokens hit (length finish_reason)
('{"id":"chatcmpl-q6r7s8t9","object":"chat.completion","created":1740067440,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"Machine learning pipelines typically involve several stages: data ingestion, feature engineering, model training, validation, and deployment. In the data ingestion phase, raw data is collected from various sources including databases, APIs, and streaming platforms. Feature engineering transforms this raw data into","refusal":null},"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":56,"completion_tokens":50,"total_tokens":106,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_q6r7s8t9"}'),

-- Multi-choice response (n=2)
('{"id":"chatcmpl-u0v1w2x3","object":"chat.completion","created":1740067500,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"Option A: Use a medallion architecture with bronze, silver, and gold layers for progressive data refinement.","refusal":null},"logprobs":null,"finish_reason":"stop"},{"index":1,"message":{"role":"assistant","content":"Option B: Implement a hub-and-spoke model where raw data lands in a central repository and domain-specific views serve each team.","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":88,"completion_tokens":64,"total_tokens":152,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_u0v1w2x3"}'),

-- Code generation response
('{"id":"chatcmpl-y4z5a6b7","object":"chat.completion","created":1740067560,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"```python\nimport pandas as pd\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\n\ndef train_model(df: pd.DataFrame, target_col: str) -> RandomForestClassifier:\n    X = df.drop(columns=[target_col])\n    y = df[target_col]\n    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n    model = RandomForestClassifier(n_estimators=100)\n    model.fit(X_train, y_train)\n    print(f\"Accuracy: {model.score(X_test, y_test):.3f}\")\n    return model\n```","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":94,"completion_tokens":186,"total_tokens":280,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_y4z5a6b7"}'),

-- Summarization response
('{"id":"chatcmpl-c8d9e0f1","object":"chat.completion","created":1740067620,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"TL;DR: The report recommends migrating legacy on-prem data warehouses to a cloud-native architecture within 18 months. Key benefits include 40% cost reduction, 3x query performance, and elastic scaling. Risks include data gravity, compliance gaps during transition, and team reskilling needs.","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":4200,"completion_tokens":72,"total_tokens":4272,"prompt_tokens_details":{"cached_tokens":4096,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_c8d9e0f1"}');


-------------------------------------------------------------------------------
-- CHAT COMPLETIONS: Tool/function calling responses
-------------------------------------------------------------------------------

INSERT INTO RAW_CHAT_COMPLETIONS (source_file, raw)
SELECT 'api_log_2026-02-20.jsonl', PARSE_JSON(column1) FROM VALUES

-- Single tool call: weather lookup
('{"id":"chatcmpl-tc01","object":"chat.completion","created":1740068000,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"call_w001","type":"function","function":{"name":"get_weather","arguments":"{\"location\":\"San Francisco, CA\",\"unit\":\"fahrenheit\"}"}}],"refusal":null},"logprobs":null,"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":82,"completion_tokens":28,"total_tokens":110,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_tc01"}'),

-- Single tool call: database query
('{"id":"chatcmpl-tc02","object":"chat.completion","created":1740068060,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"call_d001","type":"function","function":{"name":"execute_sql","arguments":"{\"query\":\"SELECT customer_name, SUM(order_total) AS lifetime_value FROM orders GROUP BY customer_name ORDER BY lifetime_value DESC LIMIT 10\",\"database\":\"analytics\"}"}}],"refusal":null},"logprobs":null,"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":156,"completion_tokens":65,"total_tokens":221,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_tc02"}'),

-- Multiple parallel tool calls
('{"id":"chatcmpl-tc03","object":"chat.completion","created":1740068120,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"call_m001","type":"function","function":{"name":"get_stock_price","arguments":"{\"symbol\":\"SNOW\"}"}},{"id":"call_m002","type":"function","function":{"name":"get_stock_price","arguments":"{\"symbol\":\"MSFT\"}"}},{"id":"call_m003","type":"function","function":{"name":"get_company_news","arguments":"{\"company\":\"Snowflake Inc\",\"days\":7}"}}],"refusal":null},"logprobs":null,"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":210,"completion_tokens":95,"total_tokens":305,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_tc03"}'),

-- Tool call with complex nested arguments
('{"id":"chatcmpl-tc04","object":"chat.completion","created":1740068180,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"call_c001","type":"function","function":{"name":"create_dashboard","arguments":"{\"title\":\"Q4 Revenue Overview\",\"charts\":[{\"type\":\"bar\",\"metric\":\"revenue\",\"groupBy\":\"region\",\"filters\":{\"quarter\":\"Q4\",\"year\":2025}},{\"type\":\"line\",\"metric\":\"growth_rate\",\"groupBy\":\"month\",\"filters\":{\"year\":2025}}],\"sharing\":{\"teams\":[\"finance\",\"executive\"],\"public\":false}}"}}],"refusal":null},"logprobs":null,"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":340,"completion_tokens":148,"total_tokens":488,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":64,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_tc04"}'),

-- Tool call + text content together
('{"id":"chatcmpl-tc05","object":"chat.completion","created":1740068240,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"I''ll look up the latest metrics for you. Let me query the database and check the current status.","tool_calls":[{"id":"call_h001","type":"function","function":{"name":"query_metrics","arguments":"{\"metric_names\":[\"cpu_utilization\",\"memory_usage\",\"disk_io\"],\"time_range\":\"last_24h\",\"aggregation\":\"avg\"}"}}],"refusal":null},"logprobs":null,"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":178,"completion_tokens":88,"total_tokens":266,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_tc05"}'),

-- Structured output (JSON mode)
('{"id":"chatcmpl-so01","object":"chat.completion","created":1740068300,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"{\"sentiment\":\"positive\",\"confidence\":0.92,\"topics\":[\"product_quality\",\"customer_service\"],\"entities\":[{\"name\":\"Acme Widget Pro\",\"type\":\"product\"},{\"name\":\"Sarah Chen\",\"type\":\"person\"}],\"summary\":\"Customer expresses high satisfaction with product quality and support responsiveness.\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":520,"completion_tokens":95,"total_tokens":615,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_so01"}'),

-- Another structured output
('{"id":"chatcmpl-so02","object":"chat.completion","created":1740068360,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"message":{"role":"assistant","content":"{\"invoice_number\":\"INV-2026-0847\",\"vendor\":\"CloudTech Solutions\",\"date\":\"2026-01-15\",\"line_items\":[{\"description\":\"Cloud Compute (Jan)\",\"quantity\":1,\"unit_price\":4500.00,\"total\":4500.00},{\"description\":\"Storage (500TB)\",\"quantity\":500,\"unit_price\":23.00,\"total\":11500.00},{\"description\":\"Support Premium\",\"quantity\":1,\"unit_price\":2000.00,\"total\":2000.00}],\"subtotal\":18000.00,\"tax\":1620.00,\"total\":19620.00,\"currency\":\"USD\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":890,"completion_tokens":210,"total_tokens":1100,"prompt_tokens_details":{"cached_tokens":0,"audio_tokens":0},"completion_tokens_details":{"reasoning_tokens":0,"audio_tokens":0,"accepted_prediction_tokens":0,"rejected_prediction_tokens":0}},"system_fingerprint":"fp_so02"}');


-------------------------------------------------------------------------------
-- BATCH API OUTPUTS
-------------------------------------------------------------------------------

INSERT INTO RAW_BATCH_OUTPUTS (source_file, raw)
SELECT 'batch_output_20260220.jsonl', PARSE_JSON(column1) FROM VALUES

-- Successful completion
('{"id":"batch_req_001","custom_id":"ticket-classify-1001","response":{"status_code":200,"request_id":"req_aaa111","body":{"id":"chatcmpl-b001","object":"chat.completion","created":1740070000,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"billing\",\"priority\":\"high\",\"sentiment\":\"negative\",\"suggested_routing\":\"billing_escalation\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":245,"completion_tokens":38,"total_tokens":283},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful completion with longer content
('{"id":"batch_req_002","custom_id":"ticket-classify-1002","response":{"status_code":200,"request_id":"req_bbb222","body":{"id":"chatcmpl-b002","object":"chat.completion","created":1740070001,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"technical_support\",\"priority\":\"medium\",\"sentiment\":\"neutral\",\"suggested_routing\":\"tier2_support\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":312,"completion_tokens":42,"total_tokens":354},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: product feedback
('{"id":"batch_req_003","custom_id":"ticket-classify-1003","response":{"status_code":200,"request_id":"req_ccc333","body":{"id":"chatcmpl-b003","object":"chat.completion","created":1740070002,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"feature_request\",\"priority\":\"low\",\"sentiment\":\"positive\",\"suggested_routing\":\"product_feedback\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":189,"completion_tokens":35,"total_tokens":224},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: account issue
('{"id":"batch_req_004","custom_id":"ticket-classify-1004","response":{"status_code":200,"request_id":"req_ddd444","body":{"id":"chatcmpl-b004","object":"chat.completion","created":1740070003,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"account_access\",\"priority\":\"high\",\"sentiment\":\"negative\",\"suggested_routing\":\"security_team\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":276,"completion_tokens":40,"total_tokens":316},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: general inquiry
('{"id":"batch_req_005","custom_id":"ticket-classify-1005","response":{"status_code":200,"request_id":"req_eee555","body":{"id":"chatcmpl-b005","object":"chat.completion","created":1740070004,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"general_inquiry\",\"priority\":\"low\",\"sentiment\":\"positive\",\"suggested_routing\":\"self_service\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":156,"completion_tokens":34,"total_tokens":190},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Rate limit error
('{"id":"batch_req_006","custom_id":"ticket-classify-1006","response":null,"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4o-mini in organization org-abc123 on tokens per min. Limit: 200000, Used: 198542, Requested: 3200."}}'),

-- Server error
('{"id":"batch_req_007","custom_id":"ticket-classify-1007","response":null,"error":{"code":"server_error","message":"The server had an error processing your request. Sorry about that!"}}'),

-- Content filter in batch
('{"id":"batch_req_008","custom_id":"ticket-classify-1008","response":{"status_code":200,"request_id":"req_fff666","body":{"id":"chatcmpl-b008","object":"chat.completion","created":1740070007,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":null,"refusal":"Content policy violation detected in input."},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":410,"completion_tokens":8,"total_tokens":418},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: urgent escalation
('{"id":"batch_req_009","custom_id":"ticket-classify-1009","response":{"status_code":200,"request_id":"req_ggg777","body":{"id":"chatcmpl-b009","object":"chat.completion","created":1740070008,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"outage_report\",\"priority\":\"critical\",\"sentiment\":\"negative\",\"suggested_routing\":\"incident_response\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":502,"completion_tokens":42,"total_tokens":544},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: compliance question
('{"id":"batch_req_010","custom_id":"ticket-classify-1010","response":{"status_code":200,"request_id":"req_hhh888","body":{"id":"chatcmpl-b010","object":"chat.completion","created":1740070009,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"compliance\",\"priority\":\"high\",\"sentiment\":\"neutral\",\"suggested_routing\":\"legal_compliance\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":388,"completion_tokens":38,"total_tokens":426},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: data export request
('{"id":"batch_req_011","custom_id":"ticket-classify-1011","response":{"status_code":200,"request_id":"req_iii999","body":{"id":"chatcmpl-b011","object":"chat.completion","created":1740070010,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"data_request\",\"priority\":\"medium\",\"sentiment\":\"neutral\",\"suggested_routing\":\"data_operations\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":267,"completion_tokens":36,"total_tokens":303},"system_fingerprint":"fp_batch01"}},"error":null}'),

-- Successful: cancellation
('{"id":"batch_req_012","custom_id":"ticket-classify-1012","response":{"status_code":200,"request_id":"req_jjj000","body":{"id":"chatcmpl-b012","object":"chat.completion","created":1740070011,"model":"gpt-4o-mini-2024-07-18","choices":[{"index":0,"message":{"role":"assistant","content":"{\"category\":\"cancellation\",\"priority\":\"high\",\"sentiment\":\"negative\",\"suggested_routing\":\"retention_team\"}","refusal":null},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":198,"completion_tokens":37,"total_tokens":235},"system_fingerprint":"fp_batch01"}},"error":null}');


-------------------------------------------------------------------------------
-- USAGE API BUCKETS (daily granularity, 14-day window)
-------------------------------------------------------------------------------

INSERT INTO RAW_USAGE_BUCKETS (source_file, raw)
SELECT 'usage_export_20260220.json', PARSE_JSON(column1) FROM VALUES

('{"object":"bucket","start_time":1739836800,"end_time":1739923200,"results":[{"object":"organization.usage.completions.result","input_tokens":285400,"output_tokens":142300,"num_model_requests":3420,"input_cached_tokens":82100,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":98200,"output_tokens":45600,"num_model_requests":1250,"input_cached_tokens":12000,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true},{"object":"organization.usage.completions.result","input_tokens":52100,"output_tokens":28900,"num_model_requests":890,"input_cached_tokens":0,"project_id":"proj_internal_tools","user_id":"user_eng_01","api_key_id":"key_dev_002","model":"gpt-4o-2024-08-06","batch":false}]}'),

('{"object":"bucket","start_time":1739923200,"end_time":1740009600,"results":[{"object":"organization.usage.completions.result","input_tokens":312800,"output_tokens":156200,"num_model_requests":3780,"input_cached_tokens":95400,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":105600,"output_tokens":48900,"num_model_requests":1380,"input_cached_tokens":14200,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true},{"object":"organization.usage.completions.result","input_tokens":48700,"output_tokens":26100,"num_model_requests":820,"input_cached_tokens":0,"project_id":"proj_internal_tools","user_id":"user_eng_01","api_key_id":"key_dev_002","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":15200,"output_tokens":8900,"num_model_requests":210,"input_cached_tokens":0,"project_id":"proj_data_pipeline","user_id":"user_eng_02","api_key_id":"key_dev_003","model":"gpt-4o-mini-2024-07-18","batch":false}]}'),

('{"object":"bucket","start_time":1740009600,"end_time":1740096000,"results":[{"object":"organization.usage.completions.result","input_tokens":298500,"output_tokens":148700,"num_model_requests":3590,"input_cached_tokens":88200,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":115800,"output_tokens":52400,"num_model_requests":1490,"input_cached_tokens":18600,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true}]}'),

('{"object":"bucket","start_time":1740096000,"end_time":1740182400,"results":[{"object":"organization.usage.completions.result","input_tokens":345200,"output_tokens":172100,"num_model_requests":4120,"input_cached_tokens":102300,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":125400,"output_tokens":58200,"num_model_requests":1620,"input_cached_tokens":22100,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true},{"object":"organization.usage.completions.result","input_tokens":67800,"output_tokens":34200,"num_model_requests":1050,"input_cached_tokens":5200,"project_id":"proj_internal_tools","user_id":"user_eng_01","api_key_id":"key_dev_002","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":22400,"output_tokens":12100,"num_model_requests":310,"input_cached_tokens":0,"project_id":"proj_data_pipeline","user_id":"user_eng_02","api_key_id":"key_dev_003","model":"gpt-4o-mini-2024-07-18","batch":false}]}'),

('{"object":"bucket","start_time":1740182400,"end_time":1740268800,"results":[{"object":"organization.usage.completions.result","input_tokens":278900,"output_tokens":138400,"num_model_requests":3340,"input_cached_tokens":78500,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":92100,"output_tokens":42800,"num_model_requests":1180,"input_cached_tokens":10800,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true},{"object":"organization.usage.completions.result","input_tokens":55300,"output_tokens":29800,"num_model_requests":920,"input_cached_tokens":2100,"project_id":"proj_internal_tools","user_id":"user_eng_01","api_key_id":"key_dev_002","model":"gpt-4o-2024-08-06","batch":false}]}'),

('{"object":"bucket","start_time":1740268800,"end_time":1740355200,"results":[{"object":"organization.usage.completions.result","input_tokens":18900,"output_tokens":9200,"num_model_requests":245,"input_cached_tokens":4200,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false},{"object":"organization.usage.completions.result","input_tokens":8400,"output_tokens":3800,"num_model_requests":98,"input_cached_tokens":800,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-mini-2024-07-18","batch":true}]}'),

('{"object":"bucket","start_time":1740355200,"end_time":1740441600,"results":[{"object":"organization.usage.completions.result","input_tokens":12400,"output_tokens":5800,"num_model_requests":158,"input_cached_tokens":2800,"project_id":"proj_customer_support","user_id":null,"api_key_id":"key_prod_001","model":"gpt-4o-2024-08-06","batch":false}]}');
